### ISSUE TITLE
Archlinux can not open google, Windows client works fine.

### ISSUE THREAD

**Issue by baozilala** [shadowsocks/shadowsocks-qt5#550]
`Connecting accounts.google.com:443 from 127.0.0.1:54896
Remote socket debug: The remote host closed the connection
Connecting accounts.google.com:443 from 127.0.0.1:54906
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54910
Connecting www.google.com:443 from 127.0.0.1:54914
Local socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54918
Local socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54922
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54926
Connecting www.google.com:443 from 127.0.0.1:54930
Remote socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54934
Local socket debug: The remote host closed the connection
Connecting www.google.com:443 from 127.0.0.1:54938
Remote socket debug: The remote host closed the connection
Remote socket debug: The remote host closed the connection`

I thought it is my server problem and i used windows shadowsocks client it works fine. In arch Linux I used this shadowsocks-qt5 and my browser can not visit pages like google, youtbe.

**Comment by librehat** [comment]
It seems that you may use a wrong configuration. Did latency test pass?

**Comment by terryding77** [comment]
Maybe you meet the same problem as #542, trying the solution `downgrade libqtshadowsocks` in that issue can help you.

**Comment by librehat** [comment]
Dupe #542

**Comment by baozilala** [comment]
Problem solved by chang encryption method from AES-256-CFB to AES-256-CTR

**Comment by amazingshuttler** [comment]
> Problem solved by chang encryption method from AES-256-CFB to AES-256-CTR

Nope, it's still not showing any better signs. Getting "Local socket: The remote host closed the connection" and also unable to use the Internet speed test website's service speedtest.net
